acc_lim_th: 1.2
acc_lim_x: 0.8
acc_lim_y: 0.8

max_vel_x: 0.5
min_vel_x: -0.5

max_vel_y: 0.5
min_vel_y: -0.5

max_trans_vel: 0.5
min_trans_vel: 0.01

max_rot_vel: 0.3
min_rot_vel: -0.3

min_in_place_vel_theta: 0.2

#param for rotating behaviour
# max_rotational_vel: 0.04
# min_in_place_rotational_vel: 0.01


sim_time: 0.5
sim_granularity: 0.01

goal_distance_bias: 30.0
path_distance_bias: 20.0
occdist_scale: 0.25

stop_time_buffer: 0.2
oscillation_reset_dist: 0.3

forward_point_distance: 0.0

scaling_speed: 0.25
max_scaling_factor: 0.2

vx_samples: 5
vy_samples: 5
vtheta_samples: 50

sim_period: 0.1

xy_goal_tolerance: 0.2 #0.3
yaw_goal_tolerance: 0.08 #0.5

rot_stopped_vel: 0.01
trans_stopped_vel: 0.01

penalize_negative_x: false
